name: Continuous Integration

on:
  push:
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Build Eureka Naming Server Container Image
        working-directory: ./naming-server
        run: mvn spring-boot:build:image -DskipTests
